---
- name: inet-Router 
  hosts: inet-Router
  become: yes
  roles:


- name: inet-Router2
  hosts: inet-Router2
  become: yes
  roles:


  - name: central-Router
  hosts: central-Router
  become: yes
  roles:


  - name: central-Server
  hosts: central-Server
  become: yes
  roles:
    - nginx

