Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.cpus = 1
  end
  # Define two VMs with static private IP addresses.
  boxes = [
    { :name => "server1",
      :ip => "192.168.60.10",
    },
    {
      :name => "server2",
      :ip => "192.168.60.15",
    }
  ]

  config.vm.provision "shell", inline: <<-SHELL
    mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
    sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    systemctl restart sshd
  SHELL

  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.network "private_network", ip: opts[:ip]

#      if opts[:name] == boxes.last[:name]
#        config.vm.provision "ansible" do |ansible|
#          ansible.playbook = "playbook.yml"
#          ansible.inventory_path = "inventory/myservers"
#          ansible.limit = "all"
#        end
#      end
    end
  end
end
