Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vm.box_check_update = false
    config.ssh.insert_key = false
  
    # ПЕРВАЯ ВИРТУАЛЬНАЯ МАШИНА
    config.vm.define "inetRouter" do |subconfig|
      subconfig.vm.provider "virtualbox" do |vb|
        vb.name = "inet-Router"
      end
      subconfig.vm.hostname = "inet-Router"
      subconfig.vm.network "private_network", ip: "192.168.53.3"
    end
  
    # ВТОРАЯ ВИРТУАЛЬНАЯ МАШИНА
    config.vm.define "inetRouter2" do |subconfig|
      subconfig.vm.provider "virtualbox" do |vb|
        vb.name = "inet-Router2"
      end
      subconfig.vm.hostname = "inet-Router2"
      subconfig.vm.network "private_network", ip: "192.168.53.4"
    end

    # ТРЕТЬЯ ВИРТУАЛЬНАЯ МАШИНА
    config.vm.define "centralRouter" do |subconfig|
        subconfig.vm.provider "virtualbox" do |vb|
          vb.name = "central-Router"
        end
        subconfig.vm.hostname = "central-Router"
        subconfig.vm.network "private_network", ip: "192.168.53.5"
        subconfig.vm.network "private_network", ip: "192.168.55.5"
    end

    # ЧЕТВЕРТАЯ ВИРТУАЛЬНАЯ МАШИНА
    config.vm.define "centralServer" do |subconfig|
        subconfig.vm.provider "virtualbox" do |vb|
          vb.name = "central-Server"
        end
        subconfig.vm.hostname = "central-Server"
        subconfig.vm.network "private_network", ip: "192.168.55.6"
    end

    config.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
        sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        systemctl restart sshd
        yum install iptables-services -y
        systemctl enable --now iptables.service
        setenforce 0
    SHELL
 
  end