---
# handlers file for rsyslog
- name: Restart rsyslog in RedHat
  service: name=rsyslog state=restarted
  when: ansible_os_family == "RedHat"

- name: Restart rsyslog in Debian
  service: name=rsyslog state=restarted
  when: ansible_os_family == "Debian"