---
# tasks file for chronyd
- name: install chronyd 
  yum: name=chrony state=latest

- name: Set time-zone
  copy:
    src: /usr/share/zoneinfo/Europe/Moscow
    dest: /etc/localtime

- name: restart chronyd
  service:
    name: chronyd
    state: restarted
    enabled: true