---
- name: web server 
  hosts: nginx
  become: yes
  roles:
    - nginx
    - audit-client-nginx
    - chronyd


- name: rsyslog server
  hosts: rsyslog
  become: yes
  roles:
    - rsyslog
    - audit-server
    - chronyd