# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
    config.vm.box = "generic/centos8"
    config.vm.provider "virtualbox" do |v|
      v.memory = 256
      v.cpus = 1
    end
  
    config.vm.define "nginx" do |nginx|
      nginx.vm.network "private_network", ip: "10.0.0.51"
      nginx.vm.hostname = "nginx"
    end
    config.vm.define "rsyslog" do |rsyslog|
      rsyslog.vm.network "private_network", ip: "10.0.0.52"
      rsyslog.vm.hostname = "rsyslog"
    end
#    config.vm.define "elk" do |elk|
#      elk.vm.network "private_network", ip: "10.0.0.53"
#      elk.vm.hostname = "elk"
#      elk.vm.provider "virtualbox" do |vb|
#        vb.memory = 4024
#        vb.cpus = 2
#      end
#    end
end