---
# tasks file for ovpn-tun-tap-server
- name: устанавливаем epel репозиторий
  yum:
    name: epel-release

- name: устанавливаем пакет openvpn, easy-rsa и iperf3
  yum:
    name:
        - easy-rsa
        - openvpn 
        - iperf3

- name: Отключаем SELinux
  selinux:
    policy: targeted
    state: permissive

- name: Проверяем наличие ключа
  stat:
    path: /etc/openvpn/static.key
  register: stat_result
- debug:
    msg: "Ключ уже существует"
  when: stat_result.stat.exists
- name: если ключ отутствует, создать его
  shell: /sbin/openvpn --genkey --secret /etc/openvpn/static.key
  when: not stat_result.stat.exists

- name: создаём конфигурационный файл vpn-сервера
  copy:
    src: server.conf
    dest: /etc/openvpn/server.conf

- name: скопировать файл-ключ static.key, на локальный хост
  fetch:
    src:  /etc/openvpn/static.key
    dest: /tmp/static.key-{{ inventory_hostname }}
    flat: yes

- name: скопировать конфигурационный файл openvpn, на локальный хост
  fetch:
    src:  /etc/openvpn/server.conf
    dest: /tmp/server.conf-{{ inventory_hostname }}
    flat: yes

- name: Запускаем openvpn сервер и добавляем в автозагрузку
  service:  
    name: openvpn@server
    state: started
    enabled: yes