---
# tasks file for ovpn-tun-tap-client
- name: устанавливаем epel репозиторий
  yum: 
    name: epel-release

- name: устанавливаем пакет openvpn, easy-rsa и iperf3
  yum: 
    name: 
      - easy-rsa
      - openvpn 
      - iperf3

- name: создаём конфигурационный файл клиента
  copy:
    src: server.conf
    dest: /etc/openvpn/server.conf

#- name: скопировать файл-ключ static.key, который был создан на сервере
#  synchronize:
#    src: /etc/openvpn/static.key
#    dest: /etc/openvpn/static.key
#    mode: pull
#  delegate_to: client

- name: скопируем файл ключа
  copy: 
    src:  /tmp/static.key-server
    dest: /etc/openvpn/static.key
    mode: 0600

- name: скопируем файл ключа
  copy: 
    src:  /tmp/server.conf-server
    dest: /etc/openvpn/server.conf
    mode: 0644
  