---
# tasks file for ovpn-tun-tap-client
- name: устанавливаем epel репозиторий
  yum: 
    name: epel-release

- name: устанавливаем пакет openvpn, easy-rsa и iperf3
  yum: 
    name: 
      - easy-rsa
      - openvpn 
      - iperf3

- name: скопируем файл ключа
  copy: 
    src:  /tmp/static.key-server
    dest: /etc/openvpn/static.key
    mode: 0600

- name: скопируем файл конфигурации
  copy: 
    src:  /tmp/server.conf-server
    dest: /etc/openvpn/server.conf
    mode: 0644

- name: Запускаем openvpn сервер и добавляем в автозагрузку
  service:  
    name: openvpn@server
    state: started
    enabled: yes