---

- name: ubuntu | Install dependencies
  apt:
    state: present
    update_cache: yes
    pkg:
       - apt-transport-https
       - ca-certificates
       - curl
       - gnupg
       - lsb-release

- name: ubuntu | Add gpg key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  notify: Update apt cache

- name: ubuntu | Add docker official repository for ubuntu
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
  notify: Update apt cache

- name: ubuntu | Install Docker Engine
  apt:
    state: present
    pkg:
       - docker-ce
       - docker-ce-cli
       - containerd.io
  notify: 
      - Start Docker service

